### ISSUE TITLE
Files in `typings\custom` are always removed during `gulp`?

### ISSUE THREAD

**Issue by Yaojian** [Justin-Credible/Ionic-TypeScript-Starter#13]
The gulp task `tsd:app` invokes `tsd reinstall`, which removes all files in the typings\custom directory and causes compilation errors.

May be `tsd update` is better than `tsd reinstall` ?

**Comment by Yaojian** [comment]
see https://github.com/Justin-Credible/Ionic-TypeScript-Starter/pull/14

**Comment by Justin-Credible** [comment]
This looks like the same issue as #9, which I can't reproduce either.

Hmm, I still can't reproduce this, even using the `tsd reinstall` command directly.

The only thing I can think of is that the version of `tsd` you are using my be different than the one that is packed with the starter. I'm using 0.6.1. Can you check your version? Are you using `./node_modules/.bin` in your path (to ensure you are using the `tsd` that is in the starter project)?

**Comment by Yaojian** [comment]
My `tsd` is `0.6.3`

**Comment by Justin-Credible** [comment]
Interesting behavior!

For now I would recommend putting `./node_modules/.bin` in your path so you can use the exact versions of the tools that the project was build for. I've gotten into the habit of doing that because I would always hit issues where newer versions of tools would change behavior and break the project.

Glad you found your issue; I'll keep this issue in mind when I upgrade the tools!
