### ISSUE TITLE
Enhancement: Obfuscate JavaScript for release

### ISSUE THREAD

**Issue by askrht** [Justin-Credible/Ionic-TypeScript-Starter#37]
I am doubtful about obfuscating HTML, but JavaScript can be obfuscated for production. Something like this:

```
    uglify = require('gulp-uglify'),
    minifyHTML = require('gulp-minify-html')

gulp.task('js', ["ts"], function() {
  var config = JSON.parse(fs.readFileSync("src/tsconfig.json", "utf8"));
  var out = config.compilerOptions.out;
  var jsBundle = out.substring(0, out.length - 3); //remove .js extension
  gulp.src(out)
    .pipe(gulpif(isReleaseScheme(), uglify()))
    .pipe(gulp.dest(jsBundle + '.min.js'));
  del([out]); // delete js/bundle.js
});

// change the index.html to use js/bundle.min.js

```

**Comment by askrht** [comment]
Please assign this issue to me. Thanks.

**Comment by Justin-Credible** [comment]
I don't think minifying the HTML is worthwhile; while the HTML will be obfuscated the developer tools can be used to inspect the DOM tree to obtain a close enough representation of the original HTML.

I would prefer not to have a separate js task. Instead the minifying could be done in the existing ts task in the completion callback. Also the minified file should be written to the same location (`www/js/bundle.js`) so that `index.html` doesn't have to be manipulated.

Finally the minification will break the loading of the application since the function passed to `run()` in `Application.js` uses parameter names for injection. An `$inject` array of strings will need to be added to `Application.ts` and passed with the existing function into `run()` so that injection will work properly when minified. eg `ngModule.run($inject, angular_initialize);`

**Comment by askrht** [comment]
Sounds good, let me take a shot at it.

**Comment by askrht** [comment]
Please assign this issue to me.

**Comment by Justin-Credible** [comment]
Go ahead and fork the repo and make your changes in a branch there and then submit a pull request and I'll take a look at it.

**Comment by Justin-Credible** [comment]
The application will fail to run after being obfuscated because there are a few areas in which Angular dependency injection is done via the names of the parameters to the methods. Since these variable names are shorted to single letters etc, they will never match the module name.

I've taken your diffs and then debugged until I found the locations to fix with annotations.

Thanks for your contribution!

**Comment by askrht** [comment]
Thank you for resolving the injection issue so fast. I have learned a lot by studying your changes.
