### ISSUE TITLE
overriding ionic scss sheets

### ISSUE THREAD

**Issue by Qvatra** [Justin-Credible/Ionic-TypeScript-Starter#45]
I've noticed that filestructure of this starter differs from initial ionic structure. for example now ionic scss files are located in bower_components folder and I need to execute >gulp libs to transfer all .css files to www/libs folder.

what is the best way to override scss ionic files in your starter?

thx.

**Comment by askrht** [comment]
You want to add a new .`scss` file under `styles/Overrides` and update `styles/Index.scss` to import your new `.scss` file.

**Comment by Qvatra** [comment]
i need to override whole _variables.scss ionic file. The problem is that i didn't find build-in functionallity to compile all ionic +  _variables.scss overriden files..
the only thing that available is >gulp libs which just copies .css files from bower folder to www/libs

offcourse I can go to bower folder and override_variables.scss file (or add reference) then perform build in this bower folder then run >gulp libs to copy files.. But I will have 2 problems:
1) my new _variables.scss file would be not under source control (because it is in bower folder)
2) it's not automated way of building app

**Comment by Justin-Credible** [comment]
I was able to achieve this using the following steps:

Create `styles/Overrides/Ionic-Variables.scss` and add the variables you want to change. I started with just copying the default color variables from `bower_components/ionic/scss/ionic.scss`. You also need to include the path to the font directory.
````
$ionicons-font-path: "../lib/ionic/fonts";

$light:                           #fff;
$stable:                          #f8f8f8;
$positive:                        #387ef5;
$calm:                            #11c1f3;
$balanced:                        #33cd5f;
$energized:                       #ffc900;
$assertive:                       #ef473a;
$royal:                           #886aea;
$dark:                            #444;
````
Add the following lines to `styles/Index.scss` to import your new variables file as well as the base Ionic SASS:
````
@import "Overrides/Ionic-Variables";
@import "../bower_components/ionic/scss/ionic";
````
Remove or comment out the css include for Ionic from `index.html`:
````
...
<!-- *** Ionic Framework (includes AngularJs) **************************************** -->

<!--<link href="lib/ionic/css/ionic.min.css" rel="stylesheet">-->
<script src="lib/ionic/js/ionic.bundle.min.js"></script>
...
````
Run `gulp sass`

Essentially what you are doing here is including the Ionic SASS source into your own SASS so it will be compiled when you run `gulp sass` instead of using Ionic's pre-built css file.

**Comment by Qvatra** [comment]
Thanks Justin! That is very helpfull - will try that

**Comment by Justin-Credible** [comment]
I've just made these changes in the project as well.
