### ISSUE TITLE
Add support for targeting mobile web apps

### ISSUE THREAD

**Issue by Justin-Credible** [Justin-Credible/Ionic-TypeScript-Starter#57]
Add additional build tasks and infrastructure to allow output of a bundle that can be served up via the web. This allows for the single codebase that is being used for iOS/Android/Chrome to also be used for a mobile website.

- [x] Add support for multiple parent scheme nodes to `gulp config`
- [x] Add `--prep web` flag for `gulp init` task that skips Cordova plugins, platforms, etc
 - [x] Investigate usage of `cordova platform add browser`
- [x] Allow for cache busting resources via query string parameter with the version number
- [x] Add support for multiple master index HTML files
 - [x] Put shared configuration in `config.yml`
 - [x] Put schemes in `schemes.yml`, remove from `config.master.xml`
 - [x] Enhance `gulp config` to populate HTML files with CSS and JS references from a common list
- [x] Build a Chrome Extension specific master HTML template
- ~~Build a mobile specific master HTML template~~ (moved to #59)
 - ~~Apple icons / splash / etc~~
 - ~~Android icons / splash / etc~~
 - ~~Loader screen~~
- [x] Add `gulp web` task to package for web
 - [x] Break `config` task into multiple functions
 - [x] Delegate to above functions
 - [x] Copy contents of `www` to `build/web`
 - [x] Strip out unnecessary files
 - [x] Bundle the contents of the js, css, lib directories to reduce the number of requests
- ~~Add utility functions to detect if a web app (also if installed/pined to home screen)~~ (moved to #59)
- [x] Gulpfile cleanup
 - [x] Switch to gulp log method
 - [x] Switch log/error strings to use `format(...)`
 - [x] Switch asynchronous `exec(...)` calls to synchronous `sh.exec(...)`
 - [x] Remove `--prep android` flag
 - [x] Use gulpfile dependencies from the `./node_modules/.bin/` directory explicitly so the user 
doesn't have to put it in their path
 - [x] Update clean paths etc
 - [x] Move gulp file helper functions to `resources/build/gulp-helpers.js`
 - [x] Move `remote-build.json` to `resources/build/remote-build.yml`
- [x] Update documentation
 - [x] Update gulp task information
 - [x] Remove prep android flag reference
 - [x] Update nvm installation instructions
 - [x] Update paths re: master files, templates, etc

**Comment by Justin-Credible** [comment]
Work is ongoing in [feature/add-web-support ](https://github.com/Justin-Credible/Ionic-TypeScript-Starter/tree/feature/add-web-support).

**Comment by Justin-Credible** [comment]
After investigating the browser platform, I'm opting to not use it for this initiative for two reasons.

First, it seems like the primary purpose of this platform is allow plugins to provider browser platform implementations so there is some minimal plugin behavior when developing in the browser. But for this project, I've already solved this issue by using a plugins service which exposes each plugin via a getter. This getter either returns the plugin implementation (when running in Cordova) or a mocked up version when running in the browser.

Second, from a couple of the plugins I've surveyed it seems like the browser platform implementations are very bare bones. While they will often work good enough for development purposes, they aren't ready for production scenarios. My plugin service allows complete control so we can interface directly with the JavaScript versions of APIs (Facebook JS SDK for example).

**Comment by askrht** [comment]
## Bundling
We are already bundling the templates, css and js. Bundling libs together with the app may not have a significant impact unless we reduce the overall size of the application. On the other hand bundling everything together will it difficult to modularize the web app at a later date. You will be forced to download the whole web app as one big chunk instead of downloading only the modules that are necessary to start with. I believe that this work can be and should deferred until we transition to Ionic 2. 

## Testing
Adding a few controller tests, integration tests, protractor, using mocks in development mode to bypass authentication etc. will make it easier to transition when the time comes.

## Mobile Web 
For mobile web, I would focus on little things like having a favicon, being able to add the bookmark to the home screen with the Application name and icon instead of the view name. These re little things that make it look professional.

## Windows 10 platform
Testing is not very sexy but Windows 10 is. It is the new old thing running on 200 million devices going to a billion. Windows 10 would be a great platform to add. Ionic team is adding Windows 10 styles to Ionic 2. I don't see them back porting these styles to Ionic 1. They appear to have moved on. Ionic 2 is definitely not ready for production. I would be happy if we can make Windows 10 run reasonably well in Ionic 1.2 itself. App will inherit the new Windows 10 styles when you upgrade to Ionic 2.

**Comment by askrht** [comment]
## Bundling
I think I misunderstood. You are bundling all the libs together in a single file but you are not bundling libs with the application js, right? I believe the sis a better solution.

**Comment by Justin-Credible** [comment]
Each asset directory will be bundled into a single file when packaging for the web:

* `lib/*.js` → `lib/app.bundle.lib.js`
* `css/*.css` → `css/app.bundle.css`
* `js/*.js` → `js/app.bundle.js`

**Comment by Justin-Credible** [comment]
Moved a few TODOs to #59.
