### ISSUE TITLE
How to add  old version of angular-resource.d.ts

### ISSUE THREAD

**Issue by six006** [Justin-Credible/Ionic-TypeScript-Starter#62]
I want to use angular-resource.d.ts in the project,but when use the command “tsd install anguar-resource" it will install the newest version,and return error .
Can you give me some advice!
Thanks!

**Comment by askrht** [comment]
That's a question for the tsd folks, not for Justin. Moreover, tsd is deprecated. I recommend moving to [typings](https://github.com/typings/typings) but there isn't a pressing need to do so until you transition to Ionic 2.

**Comment by Justin-Credible** [comment]
I was able to get it working using:

`tsd install angular-resource --save`

There was a change in the type definitions for the return value of the `$inject.get(...)` method which causes compilation errors in `HttpInterceptor.ts`. It can be fixed by adding a type cast to each of the properties.

````
        private get Utilities(): Utilities {
            return this.$injector.get(Utilities.ID);
        }
````

changes to:

````
        private get Utilities(): Utilities {
            return <Utilities>this.$injector.get(Utilities.ID);
        }
````
